handle name taken, missing git, link to remote repo, force push
MycroftAI/mycroft-skills-kit pull request #15
Opened 2018-11-24 21:16 UTC by JarbasAl

NoGitRepoException - when updating a skill there would be an exception if self.url was empty in msm
NameTakenException - if making a PR with a duplicate name

adds methods and exceptions to link to an existing repo and to force push

2018-11-25 18:40 UTC, MatthewScholefield requested changes
Looks good! Two small changes.

2018-11-25 18:40 UTC, MatthewScholefield commented on msk/actions/create.py
> +            call(['git', 'push', '-f', 'origin', 'master'],
To be consistent, this can be written as `self.git.push('origin', 'master', force=True)`

2018-11-25 18:40 UTC, MatthewScholefield commented on msk/actions/create.py
> +                call(['git', 'push', '-u', 'origin', 'master'],
Like above, this can also be: `self.git.push('origin', 'master', set_upstream=True)`

2019-01-24 18:25 UTC, JarbasAl commented
changes done

2019-05-09 05:58 UTC, forslund commented
Ping @MatthewScholefield

2019-05-23 07:21 UTC, krisgesling commented
With Matthew away I've taken a look.
Looks good to me, requested changes implemented and tested the new methods.

2019-05-23 07:22 UTC, merged