License
MycroftAI/mycroft-skills-kit pull request #24
Opened 2019-08-13 14:04 UTC by forslund

Since the skill acceptance process seem to require a license file this PR adds

- a step in the skill creation to add a license file
- a check before uploading that the license file exists

It also adds a quick and dirty check that the main description is included in the readme.

Currently checks are only made on first upload, update of skills don't check anything.

This shouldn't be considered as final but it would be interesting to show if these kinds of checks would be of interest by the skill team.

2019-08-19 00:11 UTC, krisgesling requested changes
Hey Ake, a few questions and comments, but this will be a great improvement!

2019-08-19 00:11 UTC, krisgesling commented on msk/actions/create.py
> +        print('For uploading a skill a license is required.\n'
I've found that people don't often realise what they're uploading to. Could this be something like:
> To have your Skill available for installation through the Skills Marketplace, a license is required

2019-08-19 00:11 UTC, krisgesling commented on msk/actions/upload.py
> +                  'open source licenses.')
"... for information on open source license options."
?

2019-08-19 00:11 UTC, krisgesling commented on msk/actions/upload.py
> +            print('The README lacks the About heading used for the '
It seems like this would already have been caught in `check_valid()`, is there a path that should result in this triggering?

2019-08-19 00:11 UTC, krisgesling commented on msk/actions/upload.py
> +        return
Assuming this is a typo, the rest of the method can never execute?

2019-08-19 00:11 UTC, krisgesling commented on msk/actions/create.py
>  from shutil import rmtree
If we're importing the whole package, should we update the calls to `rmtree`?

2019-08-19 00:11 UTC, krisgesling commented on msk/actions/create.py
> +    pretty = pretty.replace('-', ' ').capitalize()
Would there be a problem having the license file names capitalized correctly and removing `.capitalize()`?
```
Apache-v2.0.txt
GPL-v3.0.txt
MIT.txt
```
Seems like GPL and MIT should be all caps, but implementing this in code seems overkill.

2019-08-19 00:11 UTC, krisgesling commented on msk/actions/upload.py
> +            return
We probably need a final print line with something like: 
> "Please add the missing information and resubmit to generate a pull request"

2019-08-19 04:54 UTC, forslund commented on msk/actions/create.py
>  from shutil import rmtree
I basically import it all so it's clear where the copy is from. I don't believe there is any harm in still getting rmtree separately for convenience and readability.

2019-08-19 04:54 UTC, forslund commented on msk/actions/create.py
> +    pretty = pretty.replace('-', ' ').capitalize()
Sure I'll do the change

2019-08-19 04:56 UTC, forslund commented on msk/actions/upload.py
> +        return
This was here so the branch could be tested without actually submitting to the skills repo. For the final version this will be removed.

2019-09-27 13:00 UTC, forslund commented
I've now updated the PR from the feedback.

2019-09-27 14:38 UTC, krisgesling approved these changes

2019-09-27 14:38 UTC, krisgesling commented
Awesome-sauce!

2019-09-27 14:38 UTC, merged