make msk use token only
MycroftAI/mycroft-skills-kit pull request #33
Opened 2020-02-09 14:23 UTC by andlo

2020-02-10 09:03 UTC, forslund requested changes
I ran into some minor issues but most seems to be working great. See my comments for what I ran into and how I worked around it along with some nit-picks :)

There were some weirdness regarding to line endings, most were Unix style but some seem to be windows-style...

All in all awesome work and very readable code!

2020-02-10 09:03 UTC, forslund commented on msk/util.py
> +                        f.close()
Should probably chmod it to `600` (read-write for user only) for safety's sake

2020-02-10 09:03 UTC, forslund commented on msk/util.py
> +    r"""{token}"""
This gives me a syntax error. I needed to change it to 

```python
ASKPASS = '''#!/usr/bin/env python3
import sys
print(r"""{token}""")
'''
```

Since there is only one possible query when using the token this should be fine right?

2020-02-10 09:03 UTC, forslund commented on msk/util.py
> +                print('       [X] repo')
I still seem to need the user scope as well.

2020-02-10 09:03 UTC, forslund commented on msk/util.py
> +            f.close()
Nitpick: f.close() is not needed when using the `with open...` it's automatically closed when leaving the with context.

I think we should change the files access rights to be read/write only for the user.

```python
os.chmod(tokenfile, 0o600)
```

2020-02-10 09:03 UTC, forslund commented on msk/util.py
> +            register_git_injector(token)
this registration feels a bit out of place here...is it an extra check?

2020-02-10 10:15 UTC, andlo commented
Great - and I mostly understands what you are telling me :) I adjust later today.

I cant figure out why you need user scope and I dont.....But worth do some more investigating in.

The problem regarding lineendings could be that I copied some lines from my windows browser.....
The work is only done on theia runinig on Picroft, so a bit strange that Theia didnt fix newlines. Other issue other day ;)

2020-02-10 13:42 UTC, andlo commented
I can use token without user scope......Just tryed on other PC. 
Is what you see that git error out with "*** Please telle me who you are" and guide to set 
```
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```
if so - the #31 mentions that, and is not really in scope for token or not token....

![image](https://user-images.githubusercontent.com/3314671/74154606-3b3a7d80-4c13-11ea-80f5-ca70a11fa611.png)

2020-02-10 14:06 UTC, forslund commented
No I get an exception from github.get_user().login

I'll create a new token and retry in case I've done something else wrong

2020-02-10 15:56 UTC, forslund commented
Ok, the new token seem to work just fine :+1: wonder what's wrong with the old one...

2020-02-10 15:57 UTC, forslund commented on msk/util.py
> +                print('       [X] repo')
Not any more, this seems to be enough.

2020-02-10 17:41 UTC, andlo commented
Made the changes you pointet out and tested again with token that hasset repo scope, a token that were deleted and a working token. All seems to work as expected.

2020-02-11 07:43 UTC, forslund commented
Awesome work @andlo, works great now! Are you happy with the commit history or do you want to rebase it?

2020-02-11 12:18 UTC, andlo commented
I would like to rebase it, but need som info onhow to do that .....Do I close this PR and make a new ? are there more to it then that ?

2020-02-11 12:51 UTC, forslund commented
You don't need to close and re-open the PR, there's a pretty good introduction to rebasing [here](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history) (I usually create a backup of the branch before I start in case I mess something up)

After the rebase just do a git push -f to update the PR

2020-02-11 13:27 UTC, forslund commented
And if you're happy as is I can merge it like it is now. (I was mainly thinking about the commits without comments)

2020-02-11 15:26 UTC, andlo commented
Comits withiout comments - isnt posible, but comment three dots means the comit is a small one connectet to last "real" commit message.  :) 

Ill try rebase and se what happens - what can go wrong......;)

2020-02-11 15:39 UTC, forslund commented
Ah I usually do a `commit --amend` when doing those so it gets merged with the previous commit. Or afterwards with rebase and squash :) Like my commit history clean (so noone can see all the mistakes I make all the time!)

2020-02-11 18:49 UTC, andlo commented
hmmmthis githubing is difficult.....

What do I do step by stp.....
git checkout token_andlo (my branch where the changes are) and from where I made a PR to upstream/maste

then
git rebase (seems not to do anything)....

So can you explain (i am confused of what to do to rebase....)

2020-02-11 19:16 UTC, forslund commented
So what you want it `git rebase --interactive master`.

`git rebase master` will basically move the commits to be based on the latest commit in master, the `--interactive` allows you to do changes...

So when I'm in your branch I can run `git rebase --interactive master` and I get a text editor with

```git
pick 670f45a change to use personal access token only
pick 22e5b53 minor fixes
pick fcb1195 ...
pick 952b113 added test if token has scope repo
pick c95cc20 small comments
pick 933cbc8 ...
pick b2fc1e9 made changes Åke ointed out including minor pep8 fixes
```

this means it will pick all those commits and keep them when doing the rebase.

This can then be modified, say I want to merge the ... marked commits into the previous I change the pick to squash:

```git
pick 670f45a change to use personal access token only
pick 22e5b53 minor fixes
squash fcb1195 ...
pick 952b113 added test if token has scope repo
pick c95cc20 small comments
squash 933cbc8 ...
pick b2fc1e9 made changes Åke ointed out including minor pep8 fixes
```

And then I leave the text editor and save.

For each squash I now get the chance to update the commit message

```
# Det här är en kombination av 2 incheckningar.
# Det här är 1:a incheckningsmeddelandet:

minor fixes

# Det här är incheckningsmeddelande 2:

...

```
So I just remove the last `...` and call it done, exit and save from the text editor and do the same for the next prompt.

When I now do a `git log --pretty=oneline` I only see
```
0f6d934ed773d60a17d551f9100a7212068293f9 made changes Åke ointed out including minor pep8 fixes
0c0c874418ccc451653bec9834af72362697400d small comments
0e4e2dcc5b39814f40d2407d2a05d26dcb284e1a added test if token has scope repo
20fb3df2036def7e78ef5c4b040c009b6f7d3bdb minor fixes
670f45ad78e0a4bb0f5c2ca991b0548c7ffae700 change to use personal access token only
```

2020-02-11 19:17 UTC, forslund commented
You don't need to rebase if you don't want to, I'm good with merging it like this if you're happy with it :)

2020-02-11 19:27 UTC, andlo commented
I cant rebase atm, as my pi is working to hard, and I am not sure I can do the same on other pi (afarid something wrng happens...) So merge and I remember nex time to use the great commit --amend command for minor changes :)

2020-02-11 21:32 UTC, andlo commented
maybe did it right?

2020-02-11 21:37 UTC, forslund commented
Hmm somehow the commits are now doubled...No worries, I can clean it up tomorrow

2020-02-11 21:39 UTC, andlo commented
I knew it - I am missing some important pies of how github works....But some day when I see the light.
Thanks for helping out in such a nice way :)

2020-02-12 10:14 UTC, forslund commented
Thanks for this @andlo, Just used it to submit a skill update and it's really smooth!

With out further stalling, merging!

2020-02-12 10:14 UTC, merged